language: java

jdk:
  - oraclejdk7

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script: ./bin/travisbuild

deploy:
  provider: heroku
  api_key:
    secure: EtAWK1uqmdjlFK4zTPOtXD89SpVRefg/WifuWC34RaMXl/QI7yJPl59AQAvmzePls/ysFpUgeaPgWEVDXRHMinhJOHfBHWlLIOdrlLoqrT9wPiT7msVjZFOiFBG3jVrH+KZhHmaG9qvMFwHUEaHfqpAdRC4EVdDgVMKygy2IzqU=
  app: obscure-tor-9562
  on:
    branch: production
    repo: LeNoobs/TicTacToe

notifications:
  email:
    - bjarnia12@ru.is
    - egillh12@ru.is
    - gunnars09@ru.is
    - hildura12@ru.is
    - johanng12@ru.is
    - stefanl12@ru.is
    - tomass12@ru.is
    - thorr12@ru.is
